# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: local
    hooks:
      - id: credo-analysis
        name: Run Credo code analyzer
        entry: mix credo
        language: system
        pass_filenames: false
        stages:
          - commit
